#!/bin/bash
#openmm_dir=/home/u15684/software/openmm-7.6.0-ATMMetaForce-0.2.3/openmm-7.6.0
#openmm_dir=/home/software/openmm-7.6.0-ATMMetaForce-0.2.3/openmm-7.6.0
openmm_dir=~/Dropbox/devel/docker/openmm-7.6.0
#pythondir=/home/u15684/miniconda3
pythondir=/home/users/egallicchio/miniconda3-centos
export OPENMM_PLUGIN_DIR=${openmm_dir}/lib/plugins
export LD_LIBRARY_PATH=${openmm_dir}/lib:${openmm_dir}/lib/plugins:$LD_LIBRARY_PATH
export PYTHONPATH=${openmm_dir}/lib/python3.7/site-packages:$PYTHONPATH
${pythondir}/bin/python "$@"
